version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/home/irisowner/irisdev

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      #- --config.file=/etc/prometheus/prometheus.yml
      - --config.file=/etc/prometheus/prometheus.yml
      - '--web.enable-lifecycle'
    volumes:
      #- ./prometheus-storage/prometheus.yml:/prometheus/prometheus.yml
      - ./prometheus-storage/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      #- ./grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources