{
 "title": "URL Details Today",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Data Source", "query": "prometheus" },
   { "name": "Instance", "label": "Instance", "query": "iris:52773" },
   {
    "name": "URL",
    "query": {
     "query": "label_values(webmeasure_total_timing_in_ms, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$URL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "URL" },
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_total_hit{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_total_timing_in_ms{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Gloref",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_total_gloref{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_total_lines{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Slowest Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_max_timing{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "MAX  Gloref",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "webmeasure_max_gloref{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_average_timing_in_ms{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Gloref",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_average_gloref{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_average_lines{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "MAX Lines",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "webmeasure_max_lines{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "webmeasure_average_timing_in_ms{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average GloRef",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "webmeasure_average_gloref{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "webmeasure_average_lines{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "webmeasure_total_hit{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "webmeasure_total_timing_in_ms{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "webmeasure_total_lines{instance=\"$Instance\", id=\"$URL\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}