{
 "title": "Web Applications Summary",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": "iris:52773" },
   { "name": "DS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Day Summary $Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Instance" },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "webmeasure_total_hit{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "webmeasure_total_gloref{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "webmeasure_total_lines{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "webmeasure_total_timing_in_ms{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Slowest Average Response Time/r.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_average_timing_in_ms{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Average GlobalRef/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_average_gloref{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Average Lines/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_average_lines{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Max Response Time/r.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_max_timing{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Max GlobalRef/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_max_gloref{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Max Lines/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_max_lines{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "The average response time for each URL calculated today.  The average is reset every day at midnight.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "webmeasure_average_timing_in_ms{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Quarter Of Hour Summary $Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "webmeasure_total_hit_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "webmeasure_total_gloref_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "webmeasure_total_lines_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "webmeasure_total_timing_in_ms_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Slowest Average Response Time/r.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_average_timing_in_ms_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Average GlobalRef/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_average_gloref_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Average Lines/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_average_lines_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Max Response Time/r.",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_max_timing_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Max GlobalRef/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_max_gloref_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Top 10 URL By Max Lines/r.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "webmeasure_max_lines_current_quarter{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "The average response time for each URL calculated today.  The average is reset every day at midnight.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "webmeasure_average_timing_in_ms{instance=\"$Instance\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}