{
 "title": "BenchMark - Web Timing Tools",
 "time": { "from": "2023-07-21T11:59:33.573Z", "to": "2023-07-21T23:59:33.595Z" },
 "templating": {
  "list": [
   { "name": "timing_red", "query": "0.002" },
   { "name": "query0", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Rest Measure without logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GloRef",
   "type": "stat",
   "description": "This the number of global reference for measuring a REST request including only metrics (without request logging)",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_gloref{id=\"REST_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time for 10000 iterations on 8 parallel processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_1\"}",
     "legendFormat": "Job 1"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_2\"}",
     "legendFormat": "Job 2"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_3\"}",
     "legendFormat": "Job 3"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_4\"}",
     "legendFormat": "Job 4"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_5\"}",
     "legendFormat": "Job 5"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_6\"}",
     "legendFormat": "Job 6"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_7\"}",
     "legendFormat": "Job 7"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_0_Iteration_10000_jobnumer_8\"}",
     "legendFormat": "Job 8"
    }
   ]
  },
  {
   "title": "Average time on 8 parrallel processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A+$B+$C+$D+$E+$F+$G+$H) / 80000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Measure / second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed lines",
   "type": "stat",
   "description": "Executed lines for 1 measure without request logging",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_lines{id=\"REST_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Measure / Second per process with 8 parallel jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1/(($A+$B+$C+$D+$E+$F+$G+$H) / 80000)",
     "type": "math"
    }
   ]
  },
  { "title": "REST Measure with logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GloRef",
   "type": "stat",
   "description": "This the number of global reference for measuring a REST request including metrics and request logging.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_gloref{id=\"REST_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time for 10000 iterations on 8 parallel processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_1\"}",
     "legendFormat": "Job 1"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_2\"}",
     "legendFormat": "Job 2"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_3\"}",
     "legendFormat": "Job 3"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_4\"}",
     "legendFormat": "Job 4"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_5\"}",
     "legendFormat": "Job 5"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_6\"}",
     "legendFormat": "Job 6"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_7\"}",
     "legendFormat": "Job 7"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_8_Job(s)_Log_1_Iteration_10000_jobnumer_8\"}",
     "legendFormat": "Job 8"
    }
   ]
  },
  {
   "title": "Average time on 8 parrallel processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A+$B+$C+$D+$E+$F+$G+$H) / 80000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Measure / second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed lines",
   "type": "stat",
   "description": "Executed lines for 1 measure without request logging",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_lines{id=\"REST_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Measure / Second per process with 8 parallel jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1/(($A+$B+$C+$D+$E+$F+$G+$H) / 80000)",
     "type": "math"
    }
   ]
  },
  { "title": "CSP Measure without logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GloRef",
   "type": "stat",
   "description": "This the number of global reference for measuring a REST request including only metrics (without request logging)",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_gloref{id=\"CSP_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time for 10000 iterations on 8 parallel processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_1\"}",
     "legendFormat": "Job 1"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_2\"}",
     "legendFormat": "Job 2"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_3\"}",
     "legendFormat": "Job 3"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_4\"}",
     "legendFormat": "Job 4"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_5\"}",
     "legendFormat": "Job 5"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_6\"}",
     "legendFormat": "Job 6"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_7\"}",
     "legendFormat": "Job 7"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_0_Iteration_10000_jobnumer_8\"}",
     "legendFormat": "Job 8"
    }
   ]
  },
  {
   "title": "Average time on 8 parrallel processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A+$B+$C+$D+$E+$F+$G+$H) / 80000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Measure / second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"REST_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed lines",
   "type": "stat",
   "description": "Executed lines for 1 measure without request logging",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_lines{id=\"CSP_1_Job(s)_Log_0_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Measure / Second per process with 8 parallel jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1/(($A+$B+$C+$D+$E+$F+$G+$H) / 80000)",
     "type": "math"
    }
   ]
  },
  { "title": "CSP with request logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "GloRef",
   "type": "stat",
   "description": "This the number of global reference for measuring a REST request including metrics and request logging.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_gloref{id=\"CSP_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time for 10000 iterations on 8 parallel processes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_1\"}",
     "legendFormat": "Job 1"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_2\"}",
     "legendFormat": "Job 2"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_3\"}",
     "legendFormat": "Job 3"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_4\"}",
     "legendFormat": "Job 4"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_5\"}",
     "legendFormat": "Job 5"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_6\"}",
     "legendFormat": "Job 6"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_7\"}",
     "legendFormat": "Job 7"
    },
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_8_Job(s)_Log_1_Iteration_10000_jobnumer_8\"}",
     "legendFormat": "Job 8"
    }
   ]
  },
  {
   "title": "Average time on 8 parrallel processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A+$B+$C+$D+$E+$F+$G+$H) / 80000",
     "type": "math"
    }
   ]
  },
  {
   "title": "Measure / second",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_timing{id=\"CSP_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed lines",
   "type": "stat",
   "description": "Executed lines for 1 measure without request logging",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "webmeasure_benchmark_lines{id=\"CSP_1_Job(s)_Log_1_Iteration_1_jobnumer_1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Measure / Second per process with 8 parallel jobs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "1/(($A+$B+$C+$D+$E+$F+$G+$H) / 80000)",
     "type": "math"
    }
   ]
  }
 ]
}